import { WasmError } from '../../core/errors.ts';
import type { Disposable } from '../../core/resource-tracker.ts';

/**
 * WASM module interface — matches the wasm-bindgen generated API.
 */
export interface WasmModule {
  readonly LBFGSOptimizer: new (n: number, m: number, tolerance: number) => WasmLBFGS;
  readonly ContactConstraintEvaluator: new (threshold: number) => WasmContact;
}

export interface WasmLBFGS {
  setParameters(params: Float64Array): void;
  getParameters(): Float64Array;
  step(gradient: Float64Array): Float64Array;
  update(newX: Float64Array, newGradient: Float64Array): boolean;
  readonly iteration: number;
  reset(): void;
  free(): void;
}

export interface WasmContact {
  setGravity(gx: number, gy: number, gz: number): void;
  setContactVertices(indices: Uint32Array): void;
  evaluateContact(
    vertices: Float64Array,
    depthMap: Float64Array,
    width: number,
    height: number,
    fx: number,
    fy: number,
    cx: number,
    cy: number,
  ): Float64Array;
  free(): void;
}

let _wasmModule: WasmModule | null = null;

/**
 * Load and cache the WASM module.
 * The module is built by wasm-pack into src/backends/wasm/pkg/.
 */
export async function loadWasmModule(): Promise<WasmModule> {
  if (_wasmModule) return _wasmModule;

  try {
    // Dynamic import of wasm-pack generated module.
    // Use a variable to prevent Vite from statically analyzing the import path,
    // since the pkg/ directory is generated by `wasm-pack build` and may not exist yet.
    const wasmPath = './pkg/opencv_ts_wasm.js';
    // @ts-expect-error — module generated by wasm-pack at build time
    const mod = await import(/* @vite-ignore */ wasmPath);
    await mod.default();
    _wasmModule = mod as unknown as WasmModule;
    return _wasmModule;
  } catch (e) {
    throw new WasmError(
      `Failed to load WASM module: ${e instanceof Error ? e.message : String(e)}. ` +
        'Run `npm run wasm:build` first.',
    );
  }
}

/**
 * Wrapper that implements Disposable for WASM objects.
 */
export class WasmHandle<T extends { free(): void }> implements Disposable {
  private _inner: T | null;

  constructor(inner: T) {
    this._inner = inner;
  }

  get inner(): T {
    if (!this._inner) {
      throw new WasmError('WASM handle has been disposed.');
    }
    return this._inner;
  }

  dispose(): void {
    if (this._inner) {
      this._inner.free();
      this._inner = null;
    }
  }
}
